//-----------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a Trakt.NET source generator.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------------------------------

#nullable enable

namespace SourceGeneraterTestNamespace
{
    internal sealed partial class TestGetRequest : RequestBase
    {
        internal required string Id { get; init; }

        internal override TraktOAuthRequirement OAuthRequirement => TraktOAuthRequirement.NotRequired;

        internal TestGetRequest() : base(HttpMethod.Get, (Uri?)null) { }

        internal override void BuildUri()
        {
            string requestUri = $"notes/{Id}";
            RequestUri = new Uri(requestUri, UriKind.Relative);
        }

        internal override void Validate()
        {
            if (string.IsNullOrWhiteSpace(Id))
            {
                throw new TraktRequestValidationException(nameof(Id), "Id must not be null or empty");
            }

            if (Id.ContainsSpace())
            {
                throw new TraktRequestValidationException(nameof(Id), "Id must not contain any spaces");
            }
        }
    }
}
