//-----------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a Trakt.NET source generator.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------------------------------

#nullable enable

namespace SourceGeneraterTestNamespace
{
    internal sealed partial class TestGetRequest : RequestBase
    {
        internal override TraktOAuthRequirement OAuthRequirement => TraktOAuthRequirement.NotRequired;

        internal TestGetRequest() : base(HttpMethod.Get, (Uri?)null) { }

        internal override void BuildUri()
        {
            string requestUri = $"shows";

            requestUri = requestUri + $"?type={ListType.ToURI()}";

            RequestUri = new Uri(requestUri, UriKind.Relative);
        }

        internal override void Validate()
        {
            if (ListType == TraktListType.Unspecified)
            {
                throw new TraktRequestValidationException(nameof(ListType), "ListType must not be Unspecified");
            }
        }
    }
}
