//-----------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a Trakt.NET source generator.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------------------------------

#nullable enable

namespace SourceGeneraterTestNamespace
{
    internal sealed partial class TestGetRequest : RequestBase
    {
        internal required string Id { get; init; }

        internal override TraktOAuthRequirement OAuthRequirement => TraktOAuthRequirement.Required;

        internal TestGetRequest() : base(HttpMethod.Get, (Uri?)null) { }

        internal override void BuildUri()
        {
            string requestUri = $"notes/{Id}";
            RequestUri = new Uri(requestUri, UriKind.Relative);
        }
    }
}
