//-----------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a Trakt.NET source generator.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------------------------------

#nullable enable

namespace SourceGeneraterTestNamespace
{
    internal sealed partial class TestDeleteRequest : RequestBase
    {
        internal override TraktOAuthRequirement OAuthRequirement => TraktOAuthRequirement.NotRequired;

        internal TestDeleteRequest() : base(HttpMethod.Delete, (Uri?)null) { }

        internal override void BuildUri()
        {
            string requestUri = $"shows";

            List<string> queries = GetQueries();

            if (queries.Count > 0)
            {
                requestUri = requestUri + "?" + string.Join("&", queries);
            }

            RequestUri = new Uri(requestUri, UriKind.Relative);
        }

        private List<string> GetQueries()
        {
            List<string> queries = [];

            if (ListType.HasValue && ListType.Value != TraktListType.Unspecified)
            {
                queries.Add(ListType.Value.AsQuery());
            }

            queries.Add($"country={Country}");

            if (StartDate.HasValue)
            {
                queries.Add($"start_date={StartDate.Value.ToTraktLongDateTimeString()}");
            }

            return queries;
        }

        internal override void Validate()
        {
            if (string.IsNullOrWhiteSpace(Country))
            {
                throw new TraktRequestValidationException(nameof(Country), "Country must not be null or empty");
            }
        }
    }
}
