//-----------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a Trakt.NET source generator.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------------------------------

#nullable enable

namespace SourceGeneraterTestNamespace
{
    internal sealed partial class TestDeleteRequest : RequestBase
    {
        internal override TraktOAuthRequirement OAuthRequirement => TraktOAuthRequirement.Required;

        internal TestDeleteRequest() : base(HttpMethod.Delete, (Uri?)null) { }

        internal override void BuildUri()
            => RequestUri = new Uri("notes", UriKind.Relative);
    }
}
