namespace TraktNET.Json.People
{
    public sealed class TraktPersonShowCreditsTests
    {
        [Fact]
        public void TestTraktPersonShowCreditsDefaultConstructor()
        {
            var credits = new TraktPersonShowCredits();

            credits.Cast.ShouldBeNull();
            credits.Crew.ShouldBeNull();
        }

        [Fact]
        public async Task TestTraktPersonShowCreditsFromJson()
        {
            TraktPersonShowCredits? credits = await TestUtility.DeserializeJsonAsync<TraktPersonShowCredits>("People\\personshowcredits.json");

            credits.ShouldNotBeNull();
            credits.Cast.ShouldNotBeNull();
            credits.Cast.Count.ShouldBe(2);
            credits.Crew.ShouldNotBeNull();

            TraktPersonShowCreditsCastItem[] creditsCast = [.. credits.Cast];

            creditsCast[0].ShouldNotBeNull();
            creditsCast[0].Characters.ShouldNotBeNull();
            creditsCast[0].Characters!.Count.ShouldBe(1);
            creditsCast[0].Characters!.ShouldContain("Jon Snow");
            creditsCast[0].Show.ShouldNotBeNull();
            creditsCast[0].Show!.Title.ShouldBe("Game of Thrones");
            creditsCast[0].Show!.Year.ShouldBe(2011U);
            creditsCast[0].Show!.Airs.ShouldBeNull();
            creditsCast[0].Show!.AvailableTranslations.ShouldBeNull();
            creditsCast[0].Show!.IDs.ShouldNotBeNull();
            creditsCast[0].Show!.IDs!.Trakt.ShouldBe(1390U);
            creditsCast[0].Show!.IDs!.Slug.ShouldBe("game-of-thrones");
            creditsCast[0].Show!.IDs!.TVDB.ShouldBe(121361U);
            creditsCast[0].Show!.IDs!.IMDB.ShouldBe("tt0944947");
            creditsCast[0].Show!.IDs!.TMDB.ShouldBe(1399U);
            creditsCast[0].Show!.Genres.ShouldBeNull();
            creditsCast[0].Show!.Overview.ShouldBeNullOrEmpty();
            creditsCast[0].Show!.FirstAired.ShouldBeNull();
            creditsCast[0].Show!.Runtime.ShouldBeNull();
            creditsCast[0].Show!.Certification.ShouldBeNullOrEmpty();
            creditsCast[0].Show!.Network.ShouldBeNullOrEmpty();
            creditsCast[0].Show!.Country.ShouldBeNullOrEmpty();
            creditsCast[0].Show!.UpdatedAt.ShouldBeNull();
            creditsCast[0].Show!.Trailer.ShouldBeNullOrEmpty();
            creditsCast[0].Show!.Homepage.ShouldBeNullOrEmpty();
            creditsCast[0].Show!.Status.ShouldBeNull();
            creditsCast[0].Show!.Rating.ShouldBeNull();
            creditsCast[0].Show!.Votes.ShouldBeNull();
            creditsCast[0].Show!.Language.ShouldBeNullOrEmpty();
            creditsCast[0].Show!.AiredEpisodes.ShouldBeNull();

            creditsCast[1].ShouldNotBeNull();
            creditsCast[1].Characters.ShouldNotBeNull();
            creditsCast[1].Characters!.Count.ShouldBe(1);
            creditsCast[1].Characters!.ShouldContain("Jon Snow");
            creditsCast[1].Show.ShouldNotBeNull();
            creditsCast[1].Show!.Title.ShouldBe("Game of Thrones");
            creditsCast[1].Show!.Year.ShouldBe(2011U);
            creditsCast[1].Show!.Airs.ShouldBeNull();
            creditsCast[1].Show!.AvailableTranslations.ShouldBeNull();
            creditsCast[1].Show!.IDs.ShouldNotBeNull();
            creditsCast[1].Show!.IDs!.Trakt.ShouldBe(1390U);
            creditsCast[1].Show!.IDs!.Slug.ShouldBe("game-of-thrones");
            creditsCast[1].Show!.IDs!.TVDB.ShouldBe(121361U);
            creditsCast[1].Show!.IDs!.IMDB.ShouldBe("tt0944947");
            creditsCast[1].Show!.IDs!.TMDB.ShouldBe(1399U);
            creditsCast[1].Show!.Genres.ShouldBeNull();
            creditsCast[1].Show!.Overview.ShouldBeNullOrEmpty();
            creditsCast[1].Show!.FirstAired.ShouldBeNull();
            creditsCast[1].Show!.Runtime.ShouldBeNull();
            creditsCast[1].Show!.Certification.ShouldBeNullOrEmpty();
            creditsCast[1].Show!.Network.ShouldBeNullOrEmpty();
            creditsCast[1].Show!.Country.ShouldBeNullOrEmpty();
            creditsCast[1].Show!.UpdatedAt.ShouldBeNull();
            creditsCast[1].Show!.Trailer.ShouldBeNullOrEmpty();
            creditsCast[1].Show!.Homepage.ShouldBeNullOrEmpty();
            creditsCast[1].Show!.Status.ShouldBeNull();
            creditsCast[1].Show!.Rating.ShouldBeNull();
            creditsCast[1].Show!.Votes.ShouldBeNull();
            creditsCast[1].Show!.Language.ShouldBeNullOrEmpty();
            creditsCast[1].Show!.AiredEpisodes.ShouldBeNull();

            TraktPersonShowCreditsCrew creditsCrew = credits.Crew;

            creditsCrew.Production.ShouldNotBeNull();
            creditsCrew.Production.Count.ShouldBe(2);

            TraktPersonShowCreditsCrewItem[] productionCrew = [.. creditsCrew.Production];

            productionCrew[0].ShouldNotBeNull();
            productionCrew[0].Jobs.ShouldNotBeNull();
            productionCrew[0].Jobs!.Count.ShouldBe(1);
            productionCrew[0].Jobs!.ShouldContain("Producer 1");
            productionCrew[0].Show.ShouldNotBeNull();
            productionCrew[0].Show!.Title.ShouldBe("Game of Thrones");
            productionCrew[0].Show!.Year.ShouldBe(2011U);
            productionCrew[0].Show!.Airs.ShouldBeNull();
            productionCrew[0].Show!.AvailableTranslations.ShouldBeNull();
            productionCrew[0].Show!.IDs.ShouldNotBeNull();
            productionCrew[0].Show!.IDs!.Trakt.ShouldBe(1390U);
            productionCrew[0].Show!.IDs!.Slug.ShouldBe("game-of-thrones");
            productionCrew[0].Show!.IDs!.TVDB.ShouldBe(121361U);
            productionCrew[0].Show!.IDs!.IMDB.ShouldBe("tt0944947");
            productionCrew[0].Show!.IDs!.TMDB.ShouldBe(1399U);
            productionCrew[0].Show!.Genres.ShouldBeNull();
            productionCrew[0].Show!.Overview.ShouldBeNullOrEmpty();
            productionCrew[0].Show!.FirstAired.ShouldBeNull();
            productionCrew[0].Show!.Runtime.ShouldBeNull();
            productionCrew[0].Show!.Certification.ShouldBeNullOrEmpty();
            productionCrew[0].Show!.Network.ShouldBeNullOrEmpty();
            productionCrew[0].Show!.Country.ShouldBeNullOrEmpty();
            productionCrew[0].Show!.UpdatedAt.ShouldBeNull();
            productionCrew[0].Show!.Trailer.ShouldBeNullOrEmpty();
            productionCrew[0].Show!.Homepage.ShouldBeNullOrEmpty();
            productionCrew[0].Show!.Status.ShouldBeNull();
            productionCrew[0].Show!.Rating.ShouldBeNull();
            productionCrew[0].Show!.Votes.ShouldBeNull();
            productionCrew[0].Show!.Language.ShouldBeNullOrEmpty();
            productionCrew[0].Show!.AiredEpisodes.ShouldBeNull();

            productionCrew[1].ShouldNotBeNull();
            productionCrew[1].Jobs.ShouldNotBeNull();
            productionCrew[1].Jobs!.Count.ShouldBe(1);
            productionCrew[1].Jobs!.ShouldContain("Producer 2");
            productionCrew[1].Show.ShouldNotBeNull();
            productionCrew[1].Show!.Title.ShouldBe("Game of Thrones");
            productionCrew[1].Show!.Year.ShouldBe(2011U);
            productionCrew[1].Show!.Airs.ShouldBeNull();
            productionCrew[1].Show!.AvailableTranslations.ShouldBeNull();
            productionCrew[1].Show!.IDs.ShouldNotBeNull();
            productionCrew[1].Show!.IDs!.Trakt.ShouldBe(1390U);
            productionCrew[1].Show!.IDs!.Slug.ShouldBe("game-of-thrones");
            productionCrew[1].Show!.IDs!.TVDB.ShouldBe(121361U);
            productionCrew[1].Show!.IDs!.IMDB.ShouldBe("tt0944947");
            productionCrew[1].Show!.IDs!.TMDB.ShouldBe(1399U);
            productionCrew[1].Show!.Genres.ShouldBeNull();
            productionCrew[1].Show!.Overview.ShouldBeNullOrEmpty();
            productionCrew[1].Show!.FirstAired.ShouldBeNull();
            productionCrew[1].Show!.Runtime.ShouldBeNull();
            productionCrew[1].Show!.Certification.ShouldBeNullOrEmpty();
            productionCrew[1].Show!.Network.ShouldBeNullOrEmpty();
            productionCrew[1].Show!.Country.ShouldBeNullOrEmpty();
            productionCrew[1].Show!.UpdatedAt.ShouldBeNull();
            productionCrew[1].Show!.Trailer.ShouldBeNullOrEmpty();
            productionCrew[1].Show!.Homepage.ShouldBeNullOrEmpty();
            productionCrew[1].Show!.Status.ShouldBeNull();
            productionCrew[1].Show!.Rating.ShouldBeNull();
            productionCrew[1].Show!.Votes.ShouldBeNull();
            productionCrew[1].Show!.Language.ShouldBeNullOrEmpty();
            productionCrew[1].Show!.AiredEpisodes.ShouldBeNull();

            creditsCrew.Art.ShouldNotBeNull();
            creditsCrew.Art.Count.ShouldBe(2);

            TraktPersonShowCreditsCrewItem[] artCrew = [.. creditsCrew.Art];

            artCrew[0].ShouldNotBeNull();
            artCrew[0].Jobs.ShouldNotBeNull();
            artCrew[0].Jobs!.Count.ShouldBe(1);
            artCrew[0].Jobs!.ShouldContain("Art Director 1");
            artCrew[0].Show.ShouldNotBeNull();
            artCrew[0].Show!.Title.ShouldBe("Game of Thrones");
            artCrew[0].Show!.Year.ShouldBe(2011U);
            artCrew[0].Show!.Airs.ShouldBeNull();
            artCrew[0].Show!.AvailableTranslations.ShouldBeNull();
            artCrew[0].Show!.IDs.ShouldNotBeNull();
            artCrew[0].Show!.IDs!.Trakt.ShouldBe(1390U);
            artCrew[0].Show!.IDs!.Slug.ShouldBe("game-of-thrones");
            artCrew[0].Show!.IDs!.TVDB.ShouldBe(121361U);
            artCrew[0].Show!.IDs!.IMDB.ShouldBe("tt0944947");
            artCrew[0].Show!.IDs!.TMDB.ShouldBe(1399U);
            artCrew[0].Show!.Genres.ShouldBeNull();
            artCrew[0].Show!.Overview.ShouldBeNullOrEmpty();
            artCrew[0].Show!.FirstAired.ShouldBeNull();
            artCrew[0].Show!.Runtime.ShouldBeNull();
            artCrew[0].Show!.Certification.ShouldBeNullOrEmpty();
            artCrew[0].Show!.Network.ShouldBeNullOrEmpty();
            artCrew[0].Show!.Country.ShouldBeNullOrEmpty();
            artCrew[0].Show!.UpdatedAt.ShouldBeNull();
            artCrew[0].Show!.Trailer.ShouldBeNullOrEmpty();
            artCrew[0].Show!.Homepage.ShouldBeNullOrEmpty();
            artCrew[0].Show!.Status.ShouldBeNull();
            artCrew[0].Show!.Rating.ShouldBeNull();
            artCrew[0].Show!.Votes.ShouldBeNull();
            artCrew[0].Show!.Language.ShouldBeNullOrEmpty();
            artCrew[0].Show!.AiredEpisodes.ShouldBeNull();

            artCrew[1].ShouldNotBeNull();
            artCrew[1].Jobs.ShouldNotBeNull();
            artCrew[1].Jobs!.Count.ShouldBe(1);
            artCrew[1].Jobs!.ShouldContain("Art Director 2");
            artCrew[1].Show.ShouldNotBeNull();
            artCrew[1].Show!.Title.ShouldBe("Game of Thrones");
            artCrew[1].Show!.Year.ShouldBe(2011U);
            artCrew[1].Show!.Airs.ShouldBeNull();
            artCrew[1].Show!.AvailableTranslations.ShouldBeNull();
            artCrew[1].Show!.IDs.ShouldNotBeNull();
            artCrew[1].Show!.IDs!.Trakt.ShouldBe(1390U);
            artCrew[1].Show!.IDs!.Slug.ShouldBe("game-of-thrones");
            artCrew[1].Show!.IDs!.TVDB.ShouldBe(121361U);
            artCrew[1].Show!.IDs!.IMDB.ShouldBe("tt0944947");
            artCrew[1].Show!.IDs!.TMDB.ShouldBe(1399U);
            artCrew[1].Show!.Genres.ShouldBeNull();
            artCrew[1].Show!.Overview.ShouldBeNullOrEmpty();
            artCrew[1].Show!.FirstAired.ShouldBeNull();
            artCrew[1].Show!.Runtime.ShouldBeNull();
            artCrew[1].Show!.Certification.ShouldBeNullOrEmpty();
            artCrew[1].Show!.Network.ShouldBeNullOrEmpty();
            artCrew[1].Show!.Country.ShouldBeNullOrEmpty();
            artCrew[1].Show!.UpdatedAt.ShouldBeNull();
            artCrew[1].Show!.Trailer.ShouldBeNullOrEmpty();
            artCrew[1].Show!.Homepage.ShouldBeNullOrEmpty();
            artCrew[1].Show!.Status.ShouldBeNull();
            artCrew[1].Show!.Rating.ShouldBeNull();
            artCrew[1].Show!.Votes.ShouldBeNull();
            artCrew[1].Show!.Language.ShouldBeNullOrEmpty();
            artCrew[1].Show!.AiredEpisodes.ShouldBeNull();

            creditsCrew.Crew.ShouldNotBeNull();
            creditsCrew.Crew.Count.ShouldBe(2);

            TraktPersonShowCreditsCrewItem[] crew = [.. creditsCrew.Crew];

            crew[0].ShouldNotBeNull();
            crew[0].Jobs.ShouldNotBeNull();
            crew[0].Jobs!.Count.ShouldBe(1);
            crew[0].Jobs!.ShouldContain("Crew Member 1");
            crew[0].Show.ShouldNotBeNull();
            crew[0].Show!.Title.ShouldBe("Game of Thrones");
            crew[0].Show!.Year.ShouldBe(2011U);
            crew[0].Show!.Airs.ShouldBeNull();
            crew[0].Show!.AvailableTranslations.ShouldBeNull();
            crew[0].Show!.IDs.ShouldNotBeNull();
            crew[0].Show!.IDs!.Trakt.ShouldBe(1390U);
            crew[0].Show!.IDs!.Slug.ShouldBe("game-of-thrones");
            crew[0].Show!.IDs!.TVDB.ShouldBe(121361U);
            crew[0].Show!.IDs!.IMDB.ShouldBe("tt0944947");
            crew[0].Show!.IDs!.TMDB.ShouldBe(1399U);
            crew[0].Show!.Genres.ShouldBeNull();
            crew[0].Show!.Overview.ShouldBeNullOrEmpty();
            crew[0].Show!.FirstAired.ShouldBeNull();
            crew[0].Show!.Runtime.ShouldBeNull();
            crew[0].Show!.Certification.ShouldBeNullOrEmpty();
            crew[0].Show!.Network.ShouldBeNullOrEmpty();
            crew[0].Show!.Country.ShouldBeNullOrEmpty();
            crew[0].Show!.UpdatedAt.ShouldBeNull();
            crew[0].Show!.Trailer.ShouldBeNullOrEmpty();
            crew[0].Show!.Homepage.ShouldBeNullOrEmpty();
            crew[0].Show!.Status.ShouldBeNull();
            crew[0].Show!.Rating.ShouldBeNull();
            crew[0].Show!.Votes.ShouldBeNull();
            crew[0].Show!.Language.ShouldBeNullOrEmpty();
            crew[0].Show!.AiredEpisodes.ShouldBeNull();

            crew[1].ShouldNotBeNull();
            crew[1].Jobs.ShouldNotBeNull();
            crew[1].Jobs!.Count.ShouldBe(1);
            crew[1].Jobs!.ShouldContain("Crew Member 2");
            crew[1].Show.ShouldNotBeNull();
            crew[1].Show!.Title.ShouldBe("Game of Thrones");
            crew[1].Show!.Year.ShouldBe(2011U);
            crew[1].Show!.Airs.ShouldBeNull();
            crew[1].Show!.AvailableTranslations.ShouldBeNull();
            crew[1].Show!.IDs.ShouldNotBeNull();
            crew[1].Show!.IDs!.Trakt.ShouldBe(1390U);
            crew[1].Show!.IDs!.Slug.ShouldBe("game-of-thrones");
            crew[1].Show!.IDs!.TVDB.ShouldBe(121361U);
            crew[1].Show!.IDs!.IMDB.ShouldBe("tt0944947");
            crew[1].Show!.IDs!.TMDB.ShouldBe(1399U);
            crew[1].Show!.Genres.ShouldBeNull();
            crew[1].Show!.Overview.ShouldBeNullOrEmpty();
            crew[1].Show!.FirstAired.ShouldBeNull();
            crew[1].Show!.Runtime.ShouldBeNull();
            crew[1].Show!.Certification.ShouldBeNullOrEmpty();
            crew[1].Show!.Network.ShouldBeNullOrEmpty();
            crew[1].Show!.Country.ShouldBeNullOrEmpty();
            crew[1].Show!.UpdatedAt.ShouldBeNull();
            crew[1].Show!.Trailer.ShouldBeNullOrEmpty();
            crew[1].Show!.Homepage.ShouldBeNullOrEmpty();
            crew[1].Show!.Status.ShouldBeNull();
            crew[1].Show!.Rating.ShouldBeNull();
            crew[1].Show!.Votes.ShouldBeNull();
            crew[1].Show!.Language.ShouldBeNullOrEmpty();
            crew[1].Show!.AiredEpisodes.ShouldBeNull();

            creditsCrew.CostumeAndMakeup.ShouldNotBeNull();
            creditsCrew.CostumeAndMakeup.Count.ShouldBe(2);

            TraktPersonShowCreditsCrewItem[] costumeAndMakeupCrew = [.. creditsCrew.CostumeAndMakeup];

            costumeAndMakeupCrew[0].ShouldNotBeNull();
            costumeAndMakeupCrew[0].Jobs.ShouldNotBeNull();
            costumeAndMakeupCrew[0].Jobs!.Count.ShouldBe(1);
            costumeAndMakeupCrew[0].Jobs!.ShouldContain("Costume Designer");
            costumeAndMakeupCrew[0].Show.ShouldNotBeNull();
            costumeAndMakeupCrew[0].Show!.Title.ShouldBe("Game of Thrones");
            costumeAndMakeupCrew[0].Show!.Year.ShouldBe(2011U);
            costumeAndMakeupCrew[0].Show!.Airs.ShouldBeNull();
            costumeAndMakeupCrew[0].Show!.AvailableTranslations.ShouldBeNull();
            costumeAndMakeupCrew[0].Show!.IDs.ShouldNotBeNull();
            costumeAndMakeupCrew[0].Show!.IDs!.Trakt.ShouldBe(1390U);
            costumeAndMakeupCrew[0].Show!.IDs!.Slug.ShouldBe("game-of-thrones");
            costumeAndMakeupCrew[0].Show!.IDs!.TVDB.ShouldBe(121361U);
            costumeAndMakeupCrew[0].Show!.IDs!.IMDB.ShouldBe("tt0944947");
            costumeAndMakeupCrew[0].Show!.IDs!.TMDB.ShouldBe(1399U);
            costumeAndMakeupCrew[0].Show!.Genres.ShouldBeNull();
            costumeAndMakeupCrew[0].Show!.Overview.ShouldBeNullOrEmpty();
            costumeAndMakeupCrew[0].Show!.FirstAired.ShouldBeNull();
            costumeAndMakeupCrew[0].Show!.Runtime.ShouldBeNull();
            costumeAndMakeupCrew[0].Show!.Certification.ShouldBeNullOrEmpty();
            costumeAndMakeupCrew[0].Show!.Network.ShouldBeNullOrEmpty();
            costumeAndMakeupCrew[0].Show!.Country.ShouldBeNullOrEmpty();
            costumeAndMakeupCrew[0].Show!.UpdatedAt.ShouldBeNull();
            costumeAndMakeupCrew[0].Show!.Trailer.ShouldBeNullOrEmpty();
            costumeAndMakeupCrew[0].Show!.Homepage.ShouldBeNullOrEmpty();
            costumeAndMakeupCrew[0].Show!.Status.ShouldBeNull();
            costumeAndMakeupCrew[0].Show!.Rating.ShouldBeNull();
            costumeAndMakeupCrew[0].Show!.Votes.ShouldBeNull();
            costumeAndMakeupCrew[0].Show!.Language.ShouldBeNullOrEmpty();
            costumeAndMakeupCrew[0].Show!.AiredEpisodes.ShouldBeNull();

            costumeAndMakeupCrew[1].ShouldNotBeNull();
            costumeAndMakeupCrew[1].Jobs.ShouldNotBeNull();
            costumeAndMakeupCrew[1].Jobs!.Count.ShouldBe(1);
            costumeAndMakeupCrew[1].Jobs!.ShouldContain("Make Up Artist");
            costumeAndMakeupCrew[1].Show.ShouldNotBeNull();
            costumeAndMakeupCrew[1].Show!.Title.ShouldBe("Game of Thrones");
            costumeAndMakeupCrew[1].Show!.Year.ShouldBe(2011U);
            costumeAndMakeupCrew[1].Show!.Airs.ShouldBeNull();
            costumeAndMakeupCrew[1].Show!.AvailableTranslations.ShouldBeNull();
            costumeAndMakeupCrew[1].Show!.IDs.ShouldNotBeNull();
            costumeAndMakeupCrew[1].Show!.IDs!.Trakt.ShouldBe(1390U);
            costumeAndMakeupCrew[1].Show!.IDs!.Slug.ShouldBe("game-of-thrones");
            costumeAndMakeupCrew[1].Show!.IDs!.TVDB.ShouldBe(121361U);
            costumeAndMakeupCrew[1].Show!.IDs!.IMDB.ShouldBe("tt0944947");
            costumeAndMakeupCrew[1].Show!.IDs!.TMDB.ShouldBe(1399U);
            costumeAndMakeupCrew[1].Show!.Genres.ShouldBeNull();
            costumeAndMakeupCrew[1].Show!.Overview.ShouldBeNullOrEmpty();
            costumeAndMakeupCrew[1].Show!.FirstAired.ShouldBeNull();
            costumeAndMakeupCrew[1].Show!.Runtime.ShouldBeNull();
            costumeAndMakeupCrew[1].Show!.Certification.ShouldBeNullOrEmpty();
            costumeAndMakeupCrew[1].Show!.Network.ShouldBeNullOrEmpty();
            costumeAndMakeupCrew[1].Show!.Country.ShouldBeNullOrEmpty();
            costumeAndMakeupCrew[1].Show!.UpdatedAt.ShouldBeNull();
            costumeAndMakeupCrew[1].Show!.Trailer.ShouldBeNullOrEmpty();
            costumeAndMakeupCrew[1].Show!.Homepage.ShouldBeNullOrEmpty();
            costumeAndMakeupCrew[1].Show!.Status.ShouldBeNull();
            costumeAndMakeupCrew[1].Show!.Rating.ShouldBeNull();
            costumeAndMakeupCrew[1].Show!.Votes.ShouldBeNull();
            costumeAndMakeupCrew[1].Show!.Language.ShouldBeNullOrEmpty();
            costumeAndMakeupCrew[1].Show!.AiredEpisodes.ShouldBeNull();

            creditsCrew.Directing.ShouldNotBeNull();
            creditsCrew.Directing.Count.ShouldBe(2);

            TraktPersonShowCreditsCrewItem[] directingCrew = [.. creditsCrew.Directing];

            directingCrew[0].ShouldNotBeNull();
            directingCrew[0].Jobs.ShouldNotBeNull();
            directingCrew[0].Jobs!.Count.ShouldBe(1);
            directingCrew[0].Jobs!.ShouldContain("Director 1");
            directingCrew[0].Show.ShouldNotBeNull();
            directingCrew[0].Show!.Title.ShouldBe("Game of Thrones");
            directingCrew[0].Show!.Year.ShouldBe(2011U);
            directingCrew[0].Show!.Airs.ShouldBeNull();
            directingCrew[0].Show!.AvailableTranslations.ShouldBeNull();
            directingCrew[0].Show!.IDs.ShouldNotBeNull();
            directingCrew[0].Show!.IDs!.Trakt.ShouldBe(1390U);
            directingCrew[0].Show!.IDs!.Slug.ShouldBe("game-of-thrones");
            directingCrew[0].Show!.IDs!.TVDB.ShouldBe(121361U);
            directingCrew[0].Show!.IDs!.IMDB.ShouldBe("tt0944947");
            directingCrew[0].Show!.IDs!.TMDB.ShouldBe(1399U);
            directingCrew[0].Show!.Genres.ShouldBeNull();
            directingCrew[0].Show!.Overview.ShouldBeNullOrEmpty();
            directingCrew[0].Show!.FirstAired.ShouldBeNull();
            directingCrew[0].Show!.Runtime.ShouldBeNull();
            directingCrew[0].Show!.Certification.ShouldBeNullOrEmpty();
            directingCrew[0].Show!.Network.ShouldBeNullOrEmpty();
            directingCrew[0].Show!.Country.ShouldBeNullOrEmpty();
            directingCrew[0].Show!.UpdatedAt.ShouldBeNull();
            directingCrew[0].Show!.Trailer.ShouldBeNullOrEmpty();
            directingCrew[0].Show!.Homepage.ShouldBeNullOrEmpty();
            directingCrew[0].Show!.Status.ShouldBeNull();
            directingCrew[0].Show!.Rating.ShouldBeNull();
            directingCrew[0].Show!.Votes.ShouldBeNull();
            directingCrew[0].Show!.Language.ShouldBeNullOrEmpty();
            directingCrew[0].Show!.AiredEpisodes.ShouldBeNull();

            directingCrew[1].ShouldNotBeNull();
            directingCrew[1].Jobs.ShouldNotBeNull();
            directingCrew[1].Jobs!.Count.ShouldBe(1);
            directingCrew[1].Jobs!.ShouldContain("Director 2");
            directingCrew[1].Show.ShouldNotBeNull();
            directingCrew[1].Show!.Title.ShouldBe("Game of Thrones");
            directingCrew[1].Show!.Year.ShouldBe(2011U);
            directingCrew[1].Show!.Airs.ShouldBeNull();
            directingCrew[1].Show!.AvailableTranslations.ShouldBeNull();
            directingCrew[1].Show!.IDs.ShouldNotBeNull();
            directingCrew[1].Show!.IDs!.Trakt.ShouldBe(1390U);
            directingCrew[1].Show!.IDs!.Slug.ShouldBe("game-of-thrones");
            directingCrew[1].Show!.IDs!.TVDB.ShouldBe(121361U);
            directingCrew[1].Show!.IDs!.IMDB.ShouldBe("tt0944947");
            directingCrew[1].Show!.IDs!.TMDB.ShouldBe(1399U);
            directingCrew[1].Show!.Genres.ShouldBeNull();
            directingCrew[1].Show!.Overview.ShouldBeNullOrEmpty();
            directingCrew[1].Show!.FirstAired.ShouldBeNull();
            directingCrew[1].Show!.Runtime.ShouldBeNull();
            directingCrew[1].Show!.Certification.ShouldBeNullOrEmpty();
            directingCrew[1].Show!.Network.ShouldBeNullOrEmpty();
            directingCrew[1].Show!.Country.ShouldBeNullOrEmpty();
            directingCrew[1].Show!.UpdatedAt.ShouldBeNull();
            directingCrew[1].Show!.Trailer.ShouldBeNullOrEmpty();
            directingCrew[1].Show!.Homepage.ShouldBeNullOrEmpty();
            directingCrew[1].Show!.Status.ShouldBeNull();
            directingCrew[1].Show!.Rating.ShouldBeNull();
            directingCrew[1].Show!.Votes.ShouldBeNull();
            directingCrew[1].Show!.Language.ShouldBeNullOrEmpty();
            directingCrew[1].Show!.AiredEpisodes.ShouldBeNull();

            creditsCrew.Writing.ShouldNotBeNull();
            creditsCrew.Writing.Count.ShouldBe(2);

            TraktPersonShowCreditsCrewItem[] writingCrew = [.. creditsCrew.Writing];

            writingCrew[0].ShouldNotBeNull();
            writingCrew[0].Jobs.ShouldNotBeNull();
            writingCrew[0].Jobs!.Count.ShouldBe(1);
            writingCrew[0].Jobs!.ShouldContain("Writer 1");
            writingCrew[0].Show.ShouldNotBeNull();
            writingCrew[0].Show!.Title.ShouldBe("Game of Thrones");
            writingCrew[0].Show!.Year.ShouldBe(2011U);
            writingCrew[0].Show!.Airs.ShouldBeNull();
            writingCrew[0].Show!.AvailableTranslations.ShouldBeNull();
            writingCrew[0].Show!.IDs.ShouldNotBeNull();
            writingCrew[0].Show!.IDs!.Trakt.ShouldBe(1390U);
            writingCrew[0].Show!.IDs!.Slug.ShouldBe("game-of-thrones");
            writingCrew[0].Show!.IDs!.TVDB.ShouldBe(121361U);
            writingCrew[0].Show!.IDs!.IMDB.ShouldBe("tt0944947");
            writingCrew[0].Show!.IDs!.TMDB.ShouldBe(1399U);
            writingCrew[0].Show!.Genres.ShouldBeNull();
            writingCrew[0].Show!.Overview.ShouldBeNullOrEmpty();
            writingCrew[0].Show!.FirstAired.ShouldBeNull();
            writingCrew[0].Show!.Runtime.ShouldBeNull();
            writingCrew[0].Show!.Certification.ShouldBeNullOrEmpty();
            writingCrew[0].Show!.Network.ShouldBeNullOrEmpty();
            writingCrew[0].Show!.Country.ShouldBeNullOrEmpty();
            writingCrew[0].Show!.UpdatedAt.ShouldBeNull();
            writingCrew[0].Show!.Trailer.ShouldBeNullOrEmpty();
            writingCrew[0].Show!.Homepage.ShouldBeNullOrEmpty();
            writingCrew[0].Show!.Status.ShouldBeNull();
            writingCrew[0].Show!.Rating.ShouldBeNull();
            writingCrew[0].Show!.Votes.ShouldBeNull();
            writingCrew[0].Show!.Language.ShouldBeNullOrEmpty();
            writingCrew[0].Show!.AiredEpisodes.ShouldBeNull();

            writingCrew[1].ShouldNotBeNull();
            writingCrew[1].Jobs.ShouldNotBeNull();
            writingCrew[1].Jobs!.Count.ShouldBe(1);
            writingCrew[1].Jobs!.ShouldContain("Writer 2");
            writingCrew[1].Show.ShouldNotBeNull();
            writingCrew[1].Show!.Title.ShouldBe("Game of Thrones");
            writingCrew[1].Show!.Year.ShouldBe(2011U);
            writingCrew[1].Show!.Airs.ShouldBeNull();
            writingCrew[1].Show!.AvailableTranslations.ShouldBeNull();
            writingCrew[1].Show!.IDs.ShouldNotBeNull();
            writingCrew[1].Show!.IDs!.Trakt.ShouldBe(1390U);
            writingCrew[1].Show!.IDs!.Slug.ShouldBe("game-of-thrones");
            writingCrew[1].Show!.IDs!.TVDB.ShouldBe(121361U);
            writingCrew[1].Show!.IDs!.IMDB.ShouldBe("tt0944947");
            writingCrew[1].Show!.IDs!.TMDB.ShouldBe(1399U);
            writingCrew[1].Show!.Genres.ShouldBeNull();
            writingCrew[1].Show!.Overview.ShouldBeNullOrEmpty();
            writingCrew[1].Show!.FirstAired.ShouldBeNull();
            writingCrew[1].Show!.Runtime.ShouldBeNull();
            writingCrew[1].Show!.Certification.ShouldBeNullOrEmpty();
            writingCrew[1].Show!.Network.ShouldBeNullOrEmpty();
            writingCrew[1].Show!.Country.ShouldBeNullOrEmpty();
            writingCrew[1].Show!.UpdatedAt.ShouldBeNull();
            writingCrew[1].Show!.Trailer.ShouldBeNullOrEmpty();
            writingCrew[1].Show!.Homepage.ShouldBeNullOrEmpty();
            writingCrew[1].Show!.Status.ShouldBeNull();
            writingCrew[1].Show!.Rating.ShouldBeNull();
            writingCrew[1].Show!.Votes.ShouldBeNull();
            writingCrew[1].Show!.Language.ShouldBeNullOrEmpty();
            writingCrew[1].Show!.AiredEpisodes.ShouldBeNull();

            creditsCrew.Sound.ShouldNotBeNull();
            creditsCrew.Sound.Count.ShouldBe(2);

            TraktPersonShowCreditsCrewItem[] soundCrew = [.. creditsCrew.Sound];

            soundCrew[0].ShouldNotBeNull();
            soundCrew[0].Jobs.ShouldNotBeNull();
            soundCrew[0].Jobs!.Count.ShouldBe(1);
            soundCrew[0].Jobs!.ShouldContain("Sound Designer 1");
            soundCrew[0].Show.ShouldNotBeNull();
            soundCrew[0].Show!.Title.ShouldBe("Game of Thrones");
            soundCrew[0].Show!.Year.ShouldBe(2011U);
            soundCrew[0].Show!.Airs.ShouldBeNull();
            soundCrew[0].Show!.AvailableTranslations.ShouldBeNull();
            soundCrew[0].Show!.IDs.ShouldNotBeNull();
            soundCrew[0].Show!.IDs!.Trakt.ShouldBe(1390U);
            soundCrew[0].Show!.IDs!.Slug.ShouldBe("game-of-thrones");
            soundCrew[0].Show!.IDs!.TVDB.ShouldBe(121361U);
            soundCrew[0].Show!.IDs!.IMDB.ShouldBe("tt0944947");
            soundCrew[0].Show!.IDs!.TMDB.ShouldBe(1399U);
            soundCrew[0].Show!.Genres.ShouldBeNull();
            soundCrew[0].Show!.Overview.ShouldBeNullOrEmpty();
            soundCrew[0].Show!.FirstAired.ShouldBeNull();
            soundCrew[0].Show!.Runtime.ShouldBeNull();
            soundCrew[0].Show!.Certification.ShouldBeNullOrEmpty();
            soundCrew[0].Show!.Network.ShouldBeNullOrEmpty();
            soundCrew[0].Show!.Country.ShouldBeNullOrEmpty();
            soundCrew[0].Show!.UpdatedAt.ShouldBeNull();
            soundCrew[0].Show!.Trailer.ShouldBeNullOrEmpty();
            soundCrew[0].Show!.Homepage.ShouldBeNullOrEmpty();
            soundCrew[0].Show!.Status.ShouldBeNull();
            soundCrew[0].Show!.Rating.ShouldBeNull();
            soundCrew[0].Show!.Votes.ShouldBeNull();
            soundCrew[0].Show!.Language.ShouldBeNullOrEmpty();
            soundCrew[0].Show!.AiredEpisodes.ShouldBeNull();

            soundCrew[1].ShouldNotBeNull();
            soundCrew[1].Jobs.ShouldNotBeNull();
            soundCrew[1].Jobs!.Count.ShouldBe(1);
            soundCrew[1].Jobs!.ShouldContain("Sound Designer 2");
            soundCrew[1].Show.ShouldNotBeNull();
            soundCrew[1].Show!.Title.ShouldBe("Game of Thrones");
            soundCrew[1].Show!.Year.ShouldBe(2011U);
            soundCrew[1].Show!.Airs.ShouldBeNull();
            soundCrew[1].Show!.AvailableTranslations.ShouldBeNull();
            soundCrew[1].Show!.IDs.ShouldNotBeNull();
            soundCrew[1].Show!.IDs!.Trakt.ShouldBe(1390U);
            soundCrew[1].Show!.IDs!.Slug.ShouldBe("game-of-thrones");
            soundCrew[1].Show!.IDs!.TVDB.ShouldBe(121361U);
            soundCrew[1].Show!.IDs!.IMDB.ShouldBe("tt0944947");
            soundCrew[1].Show!.IDs!.TMDB.ShouldBe(1399U);
            soundCrew[1].Show!.Genres.ShouldBeNull();
            soundCrew[1].Show!.Overview.ShouldBeNullOrEmpty();
            soundCrew[1].Show!.FirstAired.ShouldBeNull();
            soundCrew[1].Show!.Runtime.ShouldBeNull();
            soundCrew[1].Show!.Certification.ShouldBeNullOrEmpty();
            soundCrew[1].Show!.Network.ShouldBeNullOrEmpty();
            soundCrew[1].Show!.Country.ShouldBeNullOrEmpty();
            soundCrew[1].Show!.UpdatedAt.ShouldBeNull();
            soundCrew[1].Show!.Trailer.ShouldBeNullOrEmpty();
            soundCrew[1].Show!.Homepage.ShouldBeNullOrEmpty();
            soundCrew[1].Show!.Status.ShouldBeNull();
            soundCrew[1].Show!.Rating.ShouldBeNull();
            soundCrew[1].Show!.Votes.ShouldBeNull();
            soundCrew[1].Show!.Language.ShouldBeNullOrEmpty();
            soundCrew[1].Show!.AiredEpisodes.ShouldBeNull();

            creditsCrew.Camera.ShouldNotBeNull();
            creditsCrew.Camera.Count.ShouldBe(2);

            TraktPersonShowCreditsCrewItem[] cameraCrew = [.. creditsCrew.Camera];

            cameraCrew[0].ShouldNotBeNull();
            cameraCrew[0].Jobs.ShouldNotBeNull();
            cameraCrew[0].Jobs!.Count.ShouldBe(1);
            cameraCrew[0].Jobs!.ShouldContain("Camera Man 1");
            cameraCrew[0].Show.ShouldNotBeNull();
            cameraCrew[0].Show!.Title.ShouldBe("Game of Thrones");
            cameraCrew[0].Show!.Year.ShouldBe(2011U);
            cameraCrew[0].Show!.Airs.ShouldBeNull();
            cameraCrew[0].Show!.AvailableTranslations.ShouldBeNull();
            cameraCrew[0].Show!.IDs.ShouldNotBeNull();
            cameraCrew[0].Show!.IDs!.Trakt.ShouldBe(1390U);
            cameraCrew[0].Show!.IDs!.Slug.ShouldBe("game-of-thrones");
            cameraCrew[0].Show!.IDs!.TVDB.ShouldBe(121361U);
            cameraCrew[0].Show!.IDs!.IMDB.ShouldBe("tt0944947");
            cameraCrew[0].Show!.IDs!.TMDB.ShouldBe(1399U);
            cameraCrew[0].Show!.Genres.ShouldBeNull();
            cameraCrew[0].Show!.Overview.ShouldBeNullOrEmpty();
            cameraCrew[0].Show!.FirstAired.ShouldBeNull();
            cameraCrew[0].Show!.Runtime.ShouldBeNull();
            cameraCrew[0].Show!.Certification.ShouldBeNullOrEmpty();
            cameraCrew[0].Show!.Network.ShouldBeNullOrEmpty();
            cameraCrew[0].Show!.Country.ShouldBeNullOrEmpty();
            cameraCrew[0].Show!.UpdatedAt.ShouldBeNull();
            cameraCrew[0].Show!.Trailer.ShouldBeNullOrEmpty();
            cameraCrew[0].Show!.Homepage.ShouldBeNullOrEmpty();
            cameraCrew[0].Show!.Status.ShouldBeNull();
            cameraCrew[0].Show!.Rating.ShouldBeNull();
            cameraCrew[0].Show!.Votes.ShouldBeNull();
            cameraCrew[0].Show!.Language.ShouldBeNullOrEmpty();
            cameraCrew[0].Show!.AiredEpisodes.ShouldBeNull();

            cameraCrew[1].ShouldNotBeNull();
            cameraCrew[1].Jobs.ShouldNotBeNull();
            cameraCrew[1].Jobs!.Count.ShouldBe(1);
            cameraCrew[1].Jobs!.ShouldContain("Camera Man 2");
            cameraCrew[1].Show.ShouldNotBeNull();
            cameraCrew[1].Show!.Title.ShouldBe("Game of Thrones");
            cameraCrew[1].Show!.Year.ShouldBe(2011U);
            cameraCrew[1].Show!.Airs.ShouldBeNull();
            cameraCrew[1].Show!.AvailableTranslations.ShouldBeNull();
            cameraCrew[1].Show!.IDs.ShouldNotBeNull();
            cameraCrew[1].Show!.IDs!.Trakt.ShouldBe(1390U);
            cameraCrew[1].Show!.IDs!.Slug.ShouldBe("game-of-thrones");
            cameraCrew[1].Show!.IDs!.TVDB.ShouldBe(121361U);
            cameraCrew[1].Show!.IDs!.IMDB.ShouldBe("tt0944947");
            cameraCrew[1].Show!.IDs!.TMDB.ShouldBe(1399U);
            cameraCrew[1].Show!.Genres.ShouldBeNull();
            cameraCrew[1].Show!.Overview.ShouldBeNullOrEmpty();
            cameraCrew[1].Show!.FirstAired.ShouldBeNull();
            cameraCrew[1].Show!.Runtime.ShouldBeNull();
            cameraCrew[1].Show!.Certification.ShouldBeNullOrEmpty();
            cameraCrew[1].Show!.Network.ShouldBeNullOrEmpty();
            cameraCrew[1].Show!.Country.ShouldBeNullOrEmpty();
            cameraCrew[1].Show!.UpdatedAt.ShouldBeNull();
            cameraCrew[1].Show!.Trailer.ShouldBeNullOrEmpty();
            cameraCrew[1].Show!.Homepage.ShouldBeNullOrEmpty();
            cameraCrew[1].Show!.Status.ShouldBeNull();
            cameraCrew[1].Show!.Rating.ShouldBeNull();
            cameraCrew[1].Show!.Votes.ShouldBeNull();
            cameraCrew[1].Show!.Language.ShouldBeNullOrEmpty();
            cameraCrew[1].Show!.AiredEpisodes.ShouldBeNull();

            creditsCrew.Lighting.ShouldNotBeNull();
            creditsCrew.Lighting.Count.ShouldBe(2);

            TraktPersonShowCreditsCrewItem[] lightingCrew = [.. creditsCrew.Lighting];

            lightingCrew[0].ShouldNotBeNull();
            lightingCrew[0].Jobs.ShouldNotBeNull();
            lightingCrew[0].Jobs!.Count.ShouldBe(1);
            lightingCrew[0].Jobs!.ShouldContain("Light Technician 1");
            lightingCrew[0].Show.ShouldNotBeNull();
            lightingCrew[0].Show!.Title.ShouldBe("Game of Thrones");
            lightingCrew[0].Show!.Year.ShouldBe(2011U);
            lightingCrew[0].Show!.Airs.ShouldBeNull();
            lightingCrew[0].Show!.AvailableTranslations.ShouldBeNull();
            lightingCrew[0].Show!.IDs.ShouldNotBeNull();
            lightingCrew[0].Show!.IDs!.Trakt.ShouldBe(1390U);
            lightingCrew[0].Show!.IDs!.Slug.ShouldBe("game-of-thrones");
            lightingCrew[0].Show!.IDs!.TVDB.ShouldBe(121361U);
            lightingCrew[0].Show!.IDs!.IMDB.ShouldBe("tt0944947");
            lightingCrew[0].Show!.IDs!.TMDB.ShouldBe(1399U);
            lightingCrew[0].Show!.Genres.ShouldBeNull();
            lightingCrew[0].Show!.Overview.ShouldBeNullOrEmpty();
            lightingCrew[0].Show!.FirstAired.ShouldBeNull();
            lightingCrew[0].Show!.Runtime.ShouldBeNull();
            lightingCrew[0].Show!.Certification.ShouldBeNullOrEmpty();
            lightingCrew[0].Show!.Network.ShouldBeNullOrEmpty();
            lightingCrew[0].Show!.Country.ShouldBeNullOrEmpty();
            lightingCrew[0].Show!.UpdatedAt.ShouldBeNull();
            lightingCrew[0].Show!.Trailer.ShouldBeNullOrEmpty();
            lightingCrew[0].Show!.Homepage.ShouldBeNullOrEmpty();
            lightingCrew[0].Show!.Status.ShouldBeNull();
            lightingCrew[0].Show!.Rating.ShouldBeNull();
            lightingCrew[0].Show!.Votes.ShouldBeNull();
            lightingCrew[0].Show!.Language.ShouldBeNullOrEmpty();
            lightingCrew[0].Show!.AiredEpisodes.ShouldBeNull();

            lightingCrew[1].ShouldNotBeNull();
            lightingCrew[1].Jobs.ShouldNotBeNull();
            lightingCrew[1].Jobs!.Count.ShouldBe(1);
            lightingCrew[1].Jobs!.ShouldContain("Light Technician 2");
            lightingCrew[1].Show.ShouldNotBeNull();
            lightingCrew[1].Show!.Title.ShouldBe("Game of Thrones");
            lightingCrew[1].Show!.Year.ShouldBe(2011U);
            lightingCrew[1].Show!.Airs.ShouldBeNull();
            lightingCrew[1].Show!.AvailableTranslations.ShouldBeNull();
            lightingCrew[1].Show!.IDs.ShouldNotBeNull();
            lightingCrew[1].Show!.IDs!.Trakt.ShouldBe(1390U);
            lightingCrew[1].Show!.IDs!.Slug.ShouldBe("game-of-thrones");
            lightingCrew[1].Show!.IDs!.TVDB.ShouldBe(121361U);
            lightingCrew[1].Show!.IDs!.IMDB.ShouldBe("tt0944947");
            lightingCrew[1].Show!.IDs!.TMDB.ShouldBe(1399U);
            lightingCrew[1].Show!.Genres.ShouldBeNull();
            lightingCrew[1].Show!.Overview.ShouldBeNullOrEmpty();
            lightingCrew[1].Show!.FirstAired.ShouldBeNull();
            lightingCrew[1].Show!.Runtime.ShouldBeNull();
            lightingCrew[1].Show!.Certification.ShouldBeNullOrEmpty();
            lightingCrew[1].Show!.Network.ShouldBeNullOrEmpty();
            lightingCrew[1].Show!.Country.ShouldBeNullOrEmpty();
            lightingCrew[1].Show!.UpdatedAt.ShouldBeNull();
            lightingCrew[1].Show!.Trailer.ShouldBeNullOrEmpty();
            lightingCrew[1].Show!.Homepage.ShouldBeNullOrEmpty();
            lightingCrew[1].Show!.Status.ShouldBeNull();
            lightingCrew[1].Show!.Rating.ShouldBeNull();
            lightingCrew[1].Show!.Votes.ShouldBeNull();
            lightingCrew[1].Show!.Language.ShouldBeNullOrEmpty();
            lightingCrew[1].Show!.AiredEpisodes.ShouldBeNull();

            creditsCrew.VisualEffects.ShouldNotBeNull();
            creditsCrew.VisualEffects.Count.ShouldBe(2);

            TraktPersonShowCreditsCrewItem[] vfxCrew = [.. creditsCrew.VisualEffects];

            vfxCrew[0].ShouldNotBeNull();
            vfxCrew[0].Jobs.ShouldNotBeNull();
            vfxCrew[0].Jobs!.Count.ShouldBe(1);
            vfxCrew[0].Jobs!.ShouldContain("VFX Artist 1");
            vfxCrew[0].Show.ShouldNotBeNull();
            vfxCrew[0].Show!.Title.ShouldBe("Game of Thrones");
            vfxCrew[0].Show!.Year.ShouldBe(2011U);
            vfxCrew[0].Show!.Airs.ShouldBeNull();
            vfxCrew[0].Show!.AvailableTranslations.ShouldBeNull();
            vfxCrew[0].Show!.IDs.ShouldNotBeNull();
            vfxCrew[0].Show!.IDs!.Trakt.ShouldBe(1390U);
            vfxCrew[0].Show!.IDs!.Slug.ShouldBe("game-of-thrones");
            vfxCrew[0].Show!.IDs!.TVDB.ShouldBe(121361U);
            vfxCrew[0].Show!.IDs!.IMDB.ShouldBe("tt0944947");
            vfxCrew[0].Show!.IDs!.TMDB.ShouldBe(1399U);
            vfxCrew[0].Show!.Genres.ShouldBeNull();
            vfxCrew[0].Show!.Overview.ShouldBeNullOrEmpty();
            vfxCrew[0].Show!.FirstAired.ShouldBeNull();
            vfxCrew[0].Show!.Runtime.ShouldBeNull();
            vfxCrew[0].Show!.Certification.ShouldBeNullOrEmpty();
            vfxCrew[0].Show!.Network.ShouldBeNullOrEmpty();
            vfxCrew[0].Show!.Country.ShouldBeNullOrEmpty();
            vfxCrew[0].Show!.UpdatedAt.ShouldBeNull();
            vfxCrew[0].Show!.Trailer.ShouldBeNullOrEmpty();
            vfxCrew[0].Show!.Homepage.ShouldBeNullOrEmpty();
            vfxCrew[0].Show!.Status.ShouldBeNull();
            vfxCrew[0].Show!.Rating.ShouldBeNull();
            vfxCrew[0].Show!.Votes.ShouldBeNull();
            vfxCrew[0].Show!.Language.ShouldBeNullOrEmpty();
            vfxCrew[0].Show!.AiredEpisodes.ShouldBeNull();

            vfxCrew[1].ShouldNotBeNull();
            vfxCrew[1].Jobs.ShouldNotBeNull();
            vfxCrew[1].Jobs!.Count.ShouldBe(1);
            vfxCrew[1].Jobs!.ShouldContain("VFX Artist 2");
            vfxCrew[1].Show.ShouldNotBeNull();
            vfxCrew[1].Show!.Title.ShouldBe("Game of Thrones");
            vfxCrew[1].Show!.Year.ShouldBe(2011U);
            vfxCrew[1].Show!.Airs.ShouldBeNull();
            vfxCrew[1].Show!.AvailableTranslations.ShouldBeNull();
            vfxCrew[1].Show!.IDs.ShouldNotBeNull();
            vfxCrew[1].Show!.IDs!.Trakt.ShouldBe(1390U);
            vfxCrew[1].Show!.IDs!.Slug.ShouldBe("game-of-thrones");
            vfxCrew[1].Show!.IDs!.TVDB.ShouldBe(121361U);
            vfxCrew[1].Show!.IDs!.IMDB.ShouldBe("tt0944947");
            vfxCrew[1].Show!.IDs!.TMDB.ShouldBe(1399U);
            vfxCrew[1].Show!.Genres.ShouldBeNull();
            vfxCrew[1].Show!.Overview.ShouldBeNullOrEmpty();
            vfxCrew[1].Show!.FirstAired.ShouldBeNull();
            vfxCrew[1].Show!.Runtime.ShouldBeNull();
            vfxCrew[1].Show!.Certification.ShouldBeNullOrEmpty();
            vfxCrew[1].Show!.Network.ShouldBeNullOrEmpty();
            vfxCrew[1].Show!.Country.ShouldBeNullOrEmpty();
            vfxCrew[1].Show!.UpdatedAt.ShouldBeNull();
            vfxCrew[1].Show!.Trailer.ShouldBeNullOrEmpty();
            vfxCrew[1].Show!.Homepage.ShouldBeNullOrEmpty();
            vfxCrew[1].Show!.Status.ShouldBeNull();
            vfxCrew[1].Show!.Rating.ShouldBeNull();
            vfxCrew[1].Show!.Votes.ShouldBeNull();
            vfxCrew[1].Show!.Language.ShouldBeNullOrEmpty();
            vfxCrew[1].Show!.AiredEpisodes.ShouldBeNull();

            creditsCrew.Editing.ShouldNotBeNull();
            creditsCrew.Editing.Count.ShouldBe(2);

            TraktPersonShowCreditsCrewItem[] editingCrew = [.. creditsCrew.Editing];

            editingCrew[0].ShouldNotBeNull();
            editingCrew[0].Jobs.ShouldNotBeNull();
            editingCrew[0].Jobs!.Count.ShouldBe(1);
            editingCrew[0].Jobs!.ShouldContain("Editor 1");
            editingCrew[0].Show.ShouldNotBeNull();
            editingCrew[0].Show!.Title.ShouldBe("Game of Thrones");
            editingCrew[0].Show!.Year.ShouldBe(2011U);
            editingCrew[0].Show!.Airs.ShouldBeNull();
            editingCrew[0].Show!.AvailableTranslations.ShouldBeNull();
            editingCrew[0].Show!.IDs.ShouldNotBeNull();
            editingCrew[0].Show!.IDs!.Trakt.ShouldBe(1390U);
            editingCrew[0].Show!.IDs!.Slug.ShouldBe("game-of-thrones");
            editingCrew[0].Show!.IDs!.TVDB.ShouldBe(121361U);
            editingCrew[0].Show!.IDs!.IMDB.ShouldBe("tt0944947");
            editingCrew[0].Show!.IDs!.TMDB.ShouldBe(1399U);
            editingCrew[0].Show!.Genres.ShouldBeNull();
            editingCrew[0].Show!.Overview.ShouldBeNullOrEmpty();
            editingCrew[0].Show!.FirstAired.ShouldBeNull();
            editingCrew[0].Show!.Runtime.ShouldBeNull();
            editingCrew[0].Show!.Certification.ShouldBeNullOrEmpty();
            editingCrew[0].Show!.Network.ShouldBeNullOrEmpty();
            editingCrew[0].Show!.Country.ShouldBeNullOrEmpty();
            editingCrew[0].Show!.UpdatedAt.ShouldBeNull();
            editingCrew[0].Show!.Trailer.ShouldBeNullOrEmpty();
            editingCrew[0].Show!.Homepage.ShouldBeNullOrEmpty();
            editingCrew[0].Show!.Status.ShouldBeNull();
            editingCrew[0].Show!.Rating.ShouldBeNull();
            editingCrew[0].Show!.Votes.ShouldBeNull();
            editingCrew[0].Show!.Language.ShouldBeNullOrEmpty();
            editingCrew[0].Show!.AiredEpisodes.ShouldBeNull();

            editingCrew[1].ShouldNotBeNull();
            editingCrew[1].Jobs.ShouldNotBeNull();
            editingCrew[1].Jobs!.Count.ShouldBe(1);
            editingCrew[1].Jobs!.ShouldContain("Editor 2");
            editingCrew[1].Show.ShouldNotBeNull();
            editingCrew[1].Show!.Title.ShouldBe("Game of Thrones");
            editingCrew[1].Show!.Year.ShouldBe(2011U);
            editingCrew[1].Show!.Airs.ShouldBeNull();
            editingCrew[1].Show!.AvailableTranslations.ShouldBeNull();
            editingCrew[1].Show!.IDs.ShouldNotBeNull();
            editingCrew[1].Show!.IDs!.Trakt.ShouldBe(1390U);
            editingCrew[1].Show!.IDs!.Slug.ShouldBe("game-of-thrones");
            editingCrew[1].Show!.IDs!.TVDB.ShouldBe(121361U);
            editingCrew[1].Show!.IDs!.IMDB.ShouldBe("tt0944947");
            editingCrew[1].Show!.IDs!.TMDB.ShouldBe(1399U);
            editingCrew[1].Show!.Genres.ShouldBeNull();
            editingCrew[1].Show!.Overview.ShouldBeNullOrEmpty();
            editingCrew[1].Show!.FirstAired.ShouldBeNull();
            editingCrew[1].Show!.Runtime.ShouldBeNull();
            editingCrew[1].Show!.Certification.ShouldBeNullOrEmpty();
            editingCrew[1].Show!.Network.ShouldBeNullOrEmpty();
            editingCrew[1].Show!.Country.ShouldBeNullOrEmpty();
            editingCrew[1].Show!.UpdatedAt.ShouldBeNull();
            editingCrew[1].Show!.Trailer.ShouldBeNullOrEmpty();
            editingCrew[1].Show!.Homepage.ShouldBeNullOrEmpty();
            editingCrew[1].Show!.Status.ShouldBeNull();
            editingCrew[1].Show!.Rating.ShouldBeNull();
            editingCrew[1].Show!.Votes.ShouldBeNull();
            editingCrew[1].Show!.Language.ShouldBeNullOrEmpty();
            editingCrew[1].Show!.AiredEpisodes.ShouldBeNull();
        }
    }
}
