//-----------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a Trakt.NET source generator.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------------------------------

#nullable enable

namespace SourceGeneraterTestNamespace
{
    internal sealed partial class TestPutRequest : RequestBase
    {
        internal uint? Id { get; set; }

        internal override TraktOAuthRequirement OAuthRequirement => TraktOAuthRequirement.NotRequired;

        internal TestPutRequest() : base(HttpMethod.Put, (Uri?)null) { }

        internal override void BuildUri()
        {
            string requestUri = $"notes/{Id}".Replace("//", "/");
            RequestUri = new Uri(requestUri, UriKind.Relative);
        }

        internal override void Validate()
        {
            if (Id.HasValue && Id.Value == 0)
            {
                throw new TraktRequestValidationException(nameof(Id), "Id must not be zero");
            }
        }
    }
}
