//-----------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a Trakt.NET source generator.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------------------------------

#nullable enable

namespace SourceGeneraterTestNamespace
{
    internal sealed partial class TestPostRequest : RequestBase
    {
        internal required string Id1 { get; init; }

        internal string? Id2 { get; set; }

        internal required string Id3 { get; init; }

        internal string Id4 { get; set; }

        internal required int Nr1 { get; init; }

        internal required uint Nr2 { get; init; }

        internal int? Nr3 { get; set; }

        internal uint? Nr4 { get; set; }

        internal override TraktOAuthRequirement OAuthRequirement => TraktOAuthRequirement.NotRequired;

        internal TestPostRequest() : base(HttpMethod.Post, (Uri?)null) { }

        internal override void BuildUri()
        {
            string requestUri = $"notes/{Id1}/{Id2}/{Id3}/{Id4}/{Nr1}/{Nr2}/{Nr3}/{Nr4}".Replace("//", "/");
            RequestUri = new Uri(requestUri, UriKind.Relative);
        }

        internal override void Validate()
        {
            if (string.IsNullOrWhiteSpace(Id1))
            {
                throw new TraktRequestValidationException(nameof(Id1), "Id1 must not be null or empty");
            }

            if (Id1.ContainsSpace())
            {
                throw new TraktRequestValidationException(nameof(Id1), "Id1 must not contain any spaces");
            }

            if (string.IsNullOrWhiteSpace(Id2))
            {
                throw new TraktRequestValidationException(nameof(Id2), "Id2 must not be null or empty");
            }

            if (Id2.ContainsSpace())
            {
                throw new TraktRequestValidationException(nameof(Id2), "Id2 must not contain any spaces");
            }

            if (string.IsNullOrWhiteSpace(Id3))
            {
                throw new TraktRequestValidationException(nameof(Id3), "Id3 must not be null or empty");
            }

            if (Id3.ContainsSpace())
            {
                throw new TraktRequestValidationException(nameof(Id3), "Id3 must not contain any spaces");
            }

            if (string.IsNullOrWhiteSpace(Id4))
            {
                throw new TraktRequestValidationException(nameof(Id4), "Id4 must not be null or empty");
            }

            if (Id4.ContainsSpace())
            {
                throw new TraktRequestValidationException(nameof(Id4), "Id4 must not contain any spaces");
            }

            if (Nr1 == 0)
            {
                throw new TraktRequestValidationException(nameof(Nr1), "Nr1 must not be zero");
            }

            if (Nr2 == 0)
            {
                throw new TraktRequestValidationException(nameof(Nr2), "Nr2 must not be zero");
            }

            if (Nr3.HasValue && Nr3.Value == 0)
            {
                throw new TraktRequestValidationException(nameof(Nr3), "Nr3 must not be zero");
            }

            if (Nr4.HasValue && Nr4.Value == 0)
            {
                throw new TraktRequestValidationException(nameof(Nr4), "Nr4 must not be zero");
            }
        }
    }
}
