//-----------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a Trakt.NET source generator.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------------------------------

#nullable enable

namespace SourceGeneraterTestNamespace
{
    internal sealed partial class TestPutRequest : RequestBase
    {
        internal uint? Page { get; set; }

        internal uint? Limit { get; set; }

        internal TraktOAuthRequirement OAuthRequirement { get; } = TraktOAuthRequirement.NotRequired;

        internal TestPutRequest() : base(HttpMethod.Put, (Uri?)null) { }

        internal override void BuildUri()
        {
            string requestUri = $"notes";

            if (Page.HasValue && Page.Value > 0)
            {
                requestUri = requestUri + $"?page={Page.Value}";
            }

            if (Limit.HasValue && Limit.Value > 0)
            {
                if (Page.HasValue && Page.Value > 0)
                {
                    requestUri = requestUri + $"&limit={Limit.Value}";
                }
                else
                {
                    requestUri = requestUri + $"?limit={Limit.Value}";
                }
            }

            RequestUri = new Uri(requestUri, UriKind.Relative);
        }
    }
}
