//-----------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a Trakt.NET source generator.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------------------------------

#nullable enable

using System.Text;
using System.Web;

namespace SourceGeneraterTestNamespace
{
    internal sealed partial class TestPostRequest : RequestBase
    {
        internal TraktOAuthRequirement OAuthRequirement { get; } = TraktOAuthRequirement.NotRequired;

        internal TestPostRequest() : base(HttpMethod.Post, (Uri?)null) { }

        internal override void BuildUri()
        {
            string requestUri = $"shows";

            if (StartDate.HasValue)
            {
                requestUri = requestUri + "/" + StartDate.Value.ToTraktLongDateTimeString();
            }

            string? encodedRequestUri = HttpUtility.UrlEncode(requestUri, Encoding.UTF8);
            RequestUri = new Uri(encodedRequestUri);
        }
    }
}
