//-----------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a Trakt.NET source generator.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------------------------------

#nullable enable

namespace SourceGeneraterTestNamespace
{
    internal sealed partial class TestGetRequest : RequestBase
    {
        internal TraktOAuthRequirement OAuthRequirement { get; } = TraktOAuthRequirement.Required;

        internal TestGetRequest() : base(HttpMethod.Get, (Uri?)null) { }

        internal override void BuildUri()
            => RequestUri = new Uri("notes", UriKind.Relative);
    }
}
