//-----------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a Trakt.NET source generator.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------------------------------

#nullable enable

using System.Text;
using System.Web;

namespace SourceGeneraterTestNamespace
{
    internal sealed partial class TestDeleteRequest : RequestBase
    {
        internal TraktExtendedInfo? ExtendedInfo { get; set; }

        internal uint? Page { get; set; }

        internal uint? Limit { get; set; }

        internal TraktOAuthRequirement OAuthRequirement { get; } = TraktOAuthRequirement.NotRequired;

        internal TestDeleteRequest() : base(HttpMethod.Delete, (Uri?)null) { }

        internal override void BuildUri()
        {
            string requestUri = $"shows";

            if (ListType.HasValue && ListType.Value != TraktListType.Unspecified)
            {
                requestUri = requestUri + "/" + ListType.Value.AsPathParameter();
            }

            List<string> queries = GetQueries();

            if (queries.Count > 0)
            {
                requestUri = requestUri + "?" + string.Join("&", queries);
            }

            string? encodedRequestUri = HttpUtility.UrlEncode(requestUri, Encoding.UTF8);
            RequestUri = new Uri(encodedRequestUri);
        }

        private List<string> GetQueries()
        {
            List<string> queries = [];

            if (ExtendedInfo.HasValue && ExtendedInfo.Value != TraktExtendedInfo.None)
            {
                queries.Add(ExtendedInfo.Value.AsQuery());
            }

            if (Page.HasValue && Page.Value > 0)
            {
                queries.Add($"page={Page.Value}");
            }

            if (Limit.HasValue && Limit.Value > 0)
            {
                queries.Add($"limit={Limit.Value}");
            }

            return queries;
        }
    }
}
