//-----------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a Trakt.NET source generator.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------------------------------

#nullable enable

namespace SourceGeneraterTestNamespace
{
    internal sealed partial class TestGetRequest : RequestBase
    {
        internal TraktOAuthRequirement OAuthRequirement { get; } = TraktOAuthRequirement.NotRequired;

        internal TestGetRequest() : base(HttpMethod.Get, (Uri?)null) { }

        internal override void BuildUri()
        {
            string requestUri = $"shows";

            if (StartDate.HasValue)
            {
                requestUri = requestUri + "/" + StartDate.Value.ToTraktLongDateTimeString();
            }

            RequestUri = new Uri(requestUri, UriKind.Relative);
        }
    }
}
