//-----------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a Trakt.NET source generator.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------------------------------

#nullable enable

namespace SourceGeneraterTestNamespace
{
    internal sealed partial class TestDeleteRequest : RequestBase
    {
        internal required string Id { get; init; }

        internal TraktExtendedInfo? ExtendedInfo { get; set; }

        internal uint? Page { get; set; }

        internal uint? Limit { get; set; }

        internal override TraktOAuthRequirement OAuthRequirement => TraktOAuthRequirement.Required;

        internal TestDeleteRequest() : base(HttpMethod.Delete, (Uri?)null) { }

        internal override void BuildUri()
        {
            string requestUri = $"notes/{Id}";

            List<string> queries = GetQueries();

            if (queries.Count > 0)
            {
                requestUri = requestUri + "?" + string.Join("&", queries);
            }

            RequestUri = new Uri(requestUri, UriKind.Relative);
        }

        private List<string> GetQueries()
        {
            List<string> queries = [];

            if (ExtendedInfo.HasValue && ExtendedInfo.Value != TraktExtendedInfo.None)
            {
                queries.Add(ExtendedInfo.Value.AsQuery());
            }

            if (Page.HasValue && Page.Value > 0)
            {
                queries.Add($"page={Page.Value}");
            }

            if (Limit.HasValue && Limit.Value > 0)
            {
                queries.Add($"limit={Limit.Value}");
            }

            return queries;
        }
    }
}
