//-----------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a Trakt.NET source generator.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------------------------------

#nullable enable

using System.Text;
using System.Web;

namespace SourceGeneraterTestNamespace
{
    internal sealed partial class TestDeleteRequest : RequestBase
    {
        internal TraktOAuthRequirement OAuthRequirement { get; } = TraktOAuthRequirement.NotRequired;

        internal TestDeleteRequest() : base(HttpMethod.Delete, (Uri?)null) { }

        internal override void BuildUri()
        {
            string requestUri = $"shows";

            List<string> parameters = GetParameters();

            if (parameters.Count > 0)
            {
                requestUri = requestUri + "/" + string.Join("/", parameters);
            }

            string? encodedRequestUri = HttpUtility.UrlEncode(requestUri, Encoding.UTF8);
            RequestUri = new Uri(encodedRequestUri);
        }

        private List<string> GetParameters()
        {
            List<string> parameters = [];

            if (ListType.HasValue && ListType.Value != TraktListType.Unspecified)
            {
                parameters.Add(ListType.Value.AsPathParameter());
            }

            parameters.Add(Country);

            if (StartDate.HasValue)
            {
                parameters.Add(StartDate.Value.ToTraktLongDateTimeString());
            }

            return parameters;
        }
    }
}
