//-----------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a Trakt.NET source generator.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------------------------------

#nullable enable

namespace SourceGeneraterTestNamespace
{
    internal sealed partial class TestGetRequest : RequestBase
    {
        internal TraktExtendedInfo? ExtendedInfo { get; set; }

        internal TraktOAuthRequirement OAuthRequirement { get; } = TraktOAuthRequirement.NotRequired;

        internal TestGetRequest() : base(HttpMethod.Get, (Uri?)null) { }

        internal override void BuildUri()
        {
            string requestUri = $"notes";

            if (ExtendedInfo.HasValue && ExtendedInfo.Value != TraktExtendedInfo.None)
            {
                requestUri = requestUri + "?" + ExtendedInfo.Value.AsQuery();
            }

            RequestUri = new Uri(requestUri, UriKind.Relative);
        }
    }
}
