//-----------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a Trakt.NET source generator.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------------------------------

#nullable enable

using System.Text;
using System.Web;

namespace SourceGeneraterTestNamespace
{
    internal sealed partial class TestGetRequest : RequestBase
    {
        internal TraktOAuthRequirement OAuthRequirement { get; } = TraktOAuthRequirement.NotRequired;

        internal TestGetRequest() : base(HttpMethod.Get, (Uri?)null) { }

        internal override void BuildUri()
        {
            string requestUri = $"shows";

            List<string> queries = GetQueries();

            if (queries.Count > 0)
            {
                requestUri = requestUri + "?" + string.Join("&", queries);
            }

            string? encodedRequestUri = HttpUtility.UrlEncode(requestUri, Encoding.UTF8);
            RequestUri = new Uri(encodedRequestUri);
        }

        private List<string> GetQueries()
        {
            List<string> queries = [];

            if (ListType.HasValue && ListType.Value != TraktListType.Unspecified)
            {
                queries.Add(ListType.Value.AsQuery());
            }

            queries.Add($"country={Country}");

            if (StartDate.HasValue)
            {
                queries.Add($"start_date={StartDate.Value.ToTraktLongDateTimeString()}");
            }

            return queries;
        }
    }
}
