<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Product>Trakt.NET.HttpClientFactory ($(TargetFramework))</Product>
    <Title>Trakt.NET.HttpClientFactory</Title>
    <TargetFrameworks>$(HttpClientFactoryLibraryTargetFrameworks)</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup Condition="('$(TargetFramework)' != 'net6.0') AND ('$(TargetFramework)' != 'net7.0')">
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Http" />
  </ItemGroup>

  <ItemGroup Condition="('$(TargetFramework)' == 'net6.0') OR ('$(TargetFramework)' == 'net7.0')">
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" VersionOverride="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Http" VersionOverride="8.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Trakt.NET\Trakt.NET.csproj" />
  </ItemGroup>

</Project>
