<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Product>Trakt.NET.HttpClientFactory ($(TargetFramework))</Product>
    <Title>Trakt.NET.Ex.HttpClientFactory</Title>
    <TargetFrameworks>$(HttpClientFactoryLibraryTargetFrameworks)</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Http" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Trakt.NET\Trakt.NET.Ex.csproj" />
  </ItemGroup>

</Project>
