apiRules:
- exclude:
    uidRegex: ^TraktNET\.Internal
    type: Type
- exclude:
    uidRegex: ^TraktNET\.Requests
    type: Type
- include:
    uidRegex: ^TraktNET\.Requests\.Handler\.IHttpClientProvider$
    type: Type
- include:
    uidRegex: ^TraktNET\.Requests\.Handler\.HttpClientProvider$
    type: Type
- exclude:
    uidRegex: ^TraktNET\.Core\.Constants$
    type: Type
- exclude:
    uidRegex: ^TraktNET\.Core\.DebugAsserter$
    type: Type
