<Project>

  <PropertyGroup>
    <LibraryCopyright>© 2016 - $([System.DateTime]::Now.ToString("yyyy")) by Henrik Fröhling and Contributors</LibraryCopyright>
    <LibraryTargetFrameworks>netstandard2.0;netstandard2.1;net5.0;net6.0;net7.0;net8.0</LibraryTargetFrameworks>
    <HttpClientFactoryLibraryTargetFrameworks>netstandard2.0;netstandard2.1;net6.0;net7.0;net8.0</HttpClientFactoryLibraryTargetFrameworks>
    <TestTargetFrameworks>net472;net481;net6.0;net7.0;net8.0</TestTargetFrameworks>

    <!-- These tests use Verify packages which only support these .NET versions. -->
    <SourceGenerationTestTargetFrameworks>net6.0;net7.0;net8.0</SourceGenerationTestTargetFrameworks>
  </PropertyGroup>

  <PropertyGroup>
    <IsTestProject>$(MSBuildProjectName.EndsWith('Tests'))</IsTestProject>
    <IsTestUtilityProject>$(MSBuildProjectName.EndsWith('Tests.Utility'))</IsTestUtilityProject>

    <NoWarn>1701;1702;1705;1591</NoWarn>
    <Copyright>$(LibraryCopyright)</Copyright>

    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <EnableNETAnalyzers>True</EnableNETAnalyzers>
    <AnalysisLevel>latest-recommended</AnalysisLevel>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>TraktNET</RootNamespace>
    <AccelerateBuildsInVisualStudio>true</AccelerateBuildsInVisualStudio>
    <ProduceReferenceAssembly>true</ProduceReferenceAssembly>
    <WarningLevel>7</WarningLevel>
  </PropertyGroup>

</Project>
