name: Build

on:
  workflow_call:
    inputs:
      should_run:
        required: true
        type: boolean
      environment_name:
        required: true
        type: string
      target_branch_name:
        required: true
        type: string
      working_directory:
        required: true
        type: string
      project_names:
        required: true
        type: string
      build_configuration:
        required: true
        type: string
      binaries_root_directories:
        required: true
        type: string
      artifacts_root_directory:
        required: true
        type: string
      artifacts_sub_directories:
        required: false
        type: string
      artifacts_archive_name:
        required: true
        type: string
      upload_codecov:
        required: true
        type: boolean
      push_nuget_package:
        required: true
        type: boolean

jobs:
  build:
    if: ${{ inputs.should_run }}
    runs-on: windows-latest
    environment: ${{ inputs.environment_name }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0

      - name: Build environment
        shell: bash
        run: |
          echo "Environment: ${{ inputs.environment_name }}"
          echo "Target Branch Name: ${{ inputs.target_branch_name }}"
          echo "Project Names: ${{ inputs.project_names }}"
          echo "Configuration: ${{ inputs.build_configuration }}"
          echo "Working Directory: ${{ inputs.working_directory }}"
          echo "Binaries Root Directories: ${{ inputs.binaries_root_directories }}"
          echo "Artifacts Root Directory: ${{ inputs.artifacts_root_directory }}"
          echo "Artifacts Sub Directories: ${{ inputs.artifacts_sub_directories }}"
          echo "Artifacts Archive Name: ${{ inputs.artifacts_archive_name }}"
          echo "Push NuGet Packages: ${{ inputs.push_nuget_package }}"
          echo "Upload Codecov reports: ${{ inputs.upload_codecov }}"

      - name: Setup environment variables
        uses: cardinalby/export-env-action@4f48c4676cf6ed6f46e30899ee987ce695da7c80 # v2
        with:
          envFile: './.github/constants.env'  

      - name: Setup .NET
        uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6
        with:
          dotnet-version: |
            ${{ env.DOTNET_VERSION_CURRENT_STABLE }}
            ${{ env.DOTNET_9_VERSION_STABLE }}
            ${{ env.DOTNET_8_VERSION_STABLE }}
            ${{ env.DOTNET_7_VERSION_STABLE }}
            ${{ env.DOTNET_6_VERSION_STABLE }}

      - name: Restore dependencies
        run: dotnet restore
        working-directory: ${{ inputs.working_directory }}

      - name: Build solution
        run: dotnet build  --configuration ${{ inputs.build_configuration }} --no-restore
        working-directory: ${{ inputs.working_directory }}

      - name: Run tests
        run: dotnet test --configuration ${{ inputs.build_configuration }} --no-build --no-restore /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
        working-directory: ${{ inputs.working_directory }}

      - name: Upload coverage reports to Codecov
        if: ${{ inputs.upload_codecov }}
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7

      - name: Create NuGet packages
        if: ${{ !contains(github.ref, 'pull') && !contains(github.ref, 'epic') && github.actor != 'dependabot[bot]' }}
        shell: pwsh
        run: |
          $projectNames = "${{ inputs.project_names }}" -split ";"
          foreach ($project in $projectNames) {
            dotnet pack "$project" --configuration "${{ inputs.build_configuration }}" --no-build --no-restore
          }

      - name: Copy binaries to artifacts directory
        if: ${{ !contains(github.ref, 'pull') && !contains(github.ref, 'epic') && github.actor != 'dependabot[bot]' }}
        shell: pwsh
        run: |
          $binariesRootDirectories = "${{ inputs.binaries_root_directories }}" -split ";"
          $artifactsRootDirectory = "${{ inputs.artifacts_root_directory }}"
          $hasArtifactsSubDirectories = "${{ inputs.artifacts_sub_directories }}" -ne ""
          $artifactsSubDirectories = "${{ inputs.artifacts_sub_directories }}" -split ","
          New-Item -Type Directory -Force $artifactsRootDirectory
          if ($hasArtifactsSubDirectories) {
            foreach ($directory in $artifactsSubDirectories) {
              New-Item -Type Directory -Force "$artifactsRootDirectory/$directory"
            }
          }
          foreach ($rootDirectory in $binariesRootDirectories) {
            $binariesRootDirectory = "$rootDirectory/${{ inputs.build_configuration }}"
            if (Test-Path $binariesRootDirectory) {
              if ($hasArtifactsSubDirectories) {
                $filePatterns = "Trakt.NET.*.nupkg|Trakt.NET.*.snupkg"
                $nupkgFiles = Get-ChildItem -Path $binariesRootDirectory -Recurse -ErrorAction SilentlyContinue | Where-Object { $_.Fullname -match $filePatterns }
                if ($nupkgFiles) { $nupkgFiles | Copy-Item -Destination $artifactsRootDirectory }
                $filePatterns = "Trakt.NET.*.dll|Trakt.NET.*.xml|Trakt.NET.*.pdb|Trakt.NET.*.deps.json"
                foreach ($directory in $artifactsSubDirectories) {
                  $subDir = "$binariesRootDirectory/$directory"
                  if (Test-Path $subDir) {
                    $subFiles = Get-ChildItem -Path $subDir -Recurse -ErrorAction SilentlyContinue | Where-Object { $_.Fullname -match $filePatterns }
                    if ($subFiles) { $subFiles | Copy-Item -Destination "$artifactsRootDirectory/$directory" }
                  }
                }
              } else {
                $filePatterns = "Trakt.NET.*.dll|Trakt.NET.*.xml|Trakt.NET.*.pdb|Trakt.NET.*.deps.json|Trakt.NET.*.nupkg|Trakt.NET.*.snupkg"
                $allFiles = Get-ChildItem -Path $binariesRootDirectory -Recurse -ErrorAction SilentlyContinue | Where-Object { $_.Fullname -match $filePatterns }
                if ($allFiles) { $allFiles | Copy-Item -Destination $artifactsRootDirectory }
              }
            }
          }

      - name: Upload artifacts
        if: ${{ !contains(github.ref, 'pull') && !contains(github.ref, 'epic') && github.actor != 'dependabot[bot]' }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: ${{ inputs.artifacts_archive_name }}-${{ github.run_number }}-${{ github.sha }}
          retention-days: 14
          path: '${{ inputs.artifacts_root_directory }}/'

      - name: Push NuGet packages to Github Package Registry
        if: ${{ inputs.push_nuget_package && !contains(github.ref, 'pull') && !contains(github.ref, 'epic') && github.actor != 'dependabot[bot]' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: pwsh
        run: dotnet nuget push '**/Trakt.NET*.nupkg' --api-key $env:GITHUB_TOKEN --source https://nuget.pkg.github.com/jose.farinna --skip-duplicate
        working-directory: ${{ inputs.working_directory }}

      - name: NuGet Login (Trusted Publishing via OIDC)
        if: ${{ inputs.push_nuget_package && startsWith(github.ref, 'refs/tags/v') }}
        uses: nuget/login@8d196754b4036150537f80ac539e15c2f1028841 # v1
        with:
          owner: jose.farinna
  
      - name: Push packages to NuGet
        if: ${{ inputs.push_nuget_package && startsWith(github.ref, 'refs/tags/v') }}
        shell: pwsh
        run: dotnet nuget push '**/Trakt.NET*.nupkg' --source https://api.nuget.org/v3/index.json --skip-duplicate
