name: Documentation

on:
  workflow_call:
    inputs:
      should_run:
        required: true
        type: boolean
      environment_name:
        required: true
        type: string
      project_name:
        required: true
        type: string
      build_configuration:
        required: true
        type: string
      artifacts_archive_name:
        required: true
        type: string

jobs:
  build:
    if: ${{ inputs.should_run }}
    runs-on: windows-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    environment: ${{ inputs.environment_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0

      - name: Setup environment variables
        uses: cardinalby/export-env-action@4f48c4676cf6ed6f46e30899ee987ce695da7c80 # v2
        with:
          envFile: './.github/constants.env'  

      - name: Setup .NET
        uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6
        with:
          dotnet-version: |
            ${{ env.DOTNET_VERSION_CURRENT_STABLE }}
            ${{ env.DOTNET_9_VERSION_STABLE }}
            ${{ env.DOTNET_8_VERSION_STABLE }}
            ${{ env.DOTNET_7_VERSION_STABLE }}
            ${{ env.DOTNET_6_VERSION_STABLE }}

      - name: Setup DocFX
        run: |
          dotnet tool update -g docfx || dotnet tool install -g docfx
          echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Restore dependencies
        run: dotnet restore ${{ inputs.project_name }}

      - name: Build library
        run: dotnet build ${{ inputs.project_name }} --configuration ${{ inputs.build_configuration }} --no-restore

      - name: Build documentation
        working-directory: docs
        run: |
          docfx metadata
          docfx build
          New-Item -ItemType File -Path _site/.nojekyll -Force
  
      - name: Upload documentation artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: ${{ inputs.artifacts_archive_name }}-${{ github.run_number }}-${{ github.sha }}
          retention-days: 14
          path: 'docs/_site/'

      - name: Deploy documentation
        uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453 # v4
        if: ${{ github.ref_name == 'main' || github.ref_name == 'develop' || (github.event_name == 'workflow_dispatch' && (github.ref_name == 'main' || github.ref_name == 'develop')) }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: 'docs/_site'
