name: "Static Analysis"

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/**'
      - 'Source/**'
      - 'src/**'
  pull_request:
    paths:
      - '.github/**'
      - 'Source/**'
      - 'src/**'

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: Setup environment variables
        uses: cardinalby/export-env-action@v2
        with:
          envFile: './.github/constants.env'  

      - name: Setup .NET
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: |
            ${{ env.DOTNET_VERSION_CURRENT_STABLE }}
            ${{ env.DOTNET_9_VERSION_STABLE }}
            ${{ env.DOTNET_8_VERSION_STABLE }}
            ${{ env.DOTNET_7_VERSION_STABLE }}
            ${{ env.DOTNET_6_VERSION_STABLE }}

      - name: Cache SonarCloud scanner
        id: cache-sonar-scanner
        uses: actions/cache@v4
        with:
          path: .\.sonar\scanner
          key: ${{ runner.os }}-sonar-scanner
          restore-keys: ${{ runner.os }}-sonar-scanner

      - name: Install SonarCloud scanner
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        shell: powershell
        run: |
          New-Item -Path .\.sonar\scanner -ItemType Directory -Force
          dotnet tool update dotnet-sonarscanner --tool-path .\.sonar\scanner

      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        shell: powershell
        run: |
          .\.sonar\scanner\dotnet-sonarscanner begin /k:"josefarinna_Trakt.NET" /o:"josefarinna" /n:"Trakt.NET" /d:sonar.exclusions="**/docs/**" /d:sonar.coverage.exclusions="**/tests/**,**/Tests/**" /d:sonar.cs.opencover.reportsPaths="**/coverage.opencover.xml" /d:sonar.sourceEncoding="UTF-8" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io"
          dotnet build 'src/Trakt.NET.sln' --configuration Release
          dotnet test 'src/Trakt.NET.sln' --configuration Release --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
          .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
