name: "Static Analysis"

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/**'
      - 'Source/**'
      - 'src/**'
  pull_request:
    paths:
      - '.github/**'
      - 'Source/**'
      - 'src/**'

jobs:
  stable:
    uses: ./.github/workflows/sonarcloudworkflow.yml
    secrets: inherit
    with:
      working_directory: 'Source'
      project_name: 'Source/Lib/Trakt.NET/Trakt.NET.csproj'
      build_configuration: Release
      source_exclusions: 'Source/Tests/**'

  v2-alpha:
    uses: ./.github/workflows/sonarcloudworkflow.yml
    secrets: inherit
    with:
      working_directory: 'src'
      project_name: 'src/libs/Trakt.NET/Trakt.NET.csproj'
      build_configuration: Release
      source_exclusions: 'src/tests/**'

  v2-alpha-httpclientfactory:
    uses: ./.github/workflows/sonarcloudworkflow.yml
    secrets: inherit
    with:
      working_directory: 'src'
      project_name: 'src/libs/Trakt.NET.HttpClientFactory/Trakt.NET.HttpClientFactory.csproj'
      build_configuration: Release
      source_exclusions: 'src/tests/**'
